from enum import Enum


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    CLASSIFYING = "CLASSIFYING"
    QUALITY_CHECK = "QUALITY_CHECK"
    ENHANCING = "ENHANCING"
    EXTRACTING = "EXTRACTING"
    OCR = "OCR"
    TABLE_PROCESSING = "TABLE_PROCESSING"
    FACT_EXTRACTION = "FACT_EXTRACTION"
    NORMALIZING = "NORMALIZING"
    STORING_EVIDENCE = "STORING_EVIDENCE"
    INDEX_PREPARATION = "INDEX_PREPARATION"
    VALIDATING = "VALIDATING"
    INDEXING = "INDEXING"
    ANALYZING = "ANALYZING"
    GENERATING_REPORT = "GENERATING_REPORT"
    READY = "READY"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"


class SourceType(str, Enum):
    DIGITAL_PDF = "digital_pdf"
    SCANNED_PDF = "scanned_pdf"
    XLSX = "xlsx"
    XLS = "xls"
    CSV = "csv"
    TXT = "txt"
    IMAGE = "image"
    UNKNOWN = "unknown"


class ValidationStatus(str, Enum):
    EXTRACTED = "EXTRACTED"
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    VERIFIED = "VERIFIED"
    CONFLICT = "CONFLICT"
    REJECTED = "REJECTED"


class AuditAction(str, Enum):
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_PROCESSED = "DOCUMENT_PROCESSED"
    FACT_EXTRACTED = "FACT_EXTRACTED"
    VALIDATION_CREATED = "VALIDATION_CREATED"
    FACT_APPROVED = "FACT_APPROVED"
    FACT_EDITED = "FACT_EDITED"
    FACT_REJECTED = "FACT_REJECTED"
    QUERY_EXECUTED = "QUERY_EXECUTED"
    REPORT_GENERATED = "REPORT_GENERATED"
    PDF_EXPORTED = "PDF_EXPORTED"
    DOCUMENT_DELETED = "DOCUMENT_DELETED"
    SYSTEM_CONFIG_CHANGED = "SYSTEM_CONFIG_CHANGED"


class FileType(str, Enum):
    PDF = "PDF"
    XLSX = "XLSX"
    XLS = "XLS"
    CSV = "CSV"
    TXT = "TXT"
    PNG = "PNG"
    JPG = "JPG"
    JPEG = "JPEG"
    UNKNOWN = "UNKNOWN"


class ExtractionMethod(str, Enum):
    STRUCTURED_TABLE = "STRUCTURED_TABLE"
    HEURISTIC_PARSER = "HEURISTIC_PARSER"
    REGEX_PATTERN = "REGEX_PATTERN"
    OCR_BLOCK = "OCR_BLOCK"
    LLM_ASSISTED = "LLM_ASSISTED"
    MANUAL_ENTRY = "MANUAL_ENTRY"
