from enum import Enum


class DocumentStatus(str, Enum):
    UPLOADED = "UPLOADED"
    QUEUED = "QUEUED"
    CLASSIFYING = "CLASSIFYING"
    QUALITY_CHECK = "QUALITY_CHECK"
    ENHANCING = "ENHANCING"
    EXTRACTING = "EXTRACTING"
    OCR = "OCR"
    TABLE_PROCESSING = "TABLE_PROCESSING"
    FACT_EXTRACTION = "FACT_EXTRACTION"
    NORMALIZING = "NORMALIZING"
    STORING_EVIDENCE = "STORING_EVIDENCE"
    INDEX_PREPARATION = "INDEX_PREPARATION"
    VALIDATING = "VALIDATING"
    INDEXING = "INDEXING"
    ANALYZING = "ANALYZING"
    GENERATING_REPORT = "GENERATING_REPORT"
    READY = "READY"
    COMPLETED_WITH_WARNINGS = "COMPLETED_WITH_WARNINGS"
    FAILED = "FAILED"


class SourceType(str, Enum):
    DIGITAL_PDF = "digital_pdf"
    SCANNED_PDF = "scanned_pdf"
    XLSX = "xlsx"
    XLS = "xls"
    CSV = "csv"
    TXT = "txt"
    IMAGE = "image"
    UNKNOWN = "unknown"


class ValidationStatus(str, Enum):
    EXTRACTED = "EXTRACTED"
    HIGH_CONFIDENCE = "HIGH_CONFIDENCE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    VERIFIED = "VERIFIED"
    CONFLICT = "CONFLICT"
    REJECTED = "REJECTED"
    SUPERSEDED = "SUPERSEDED"
    DUPLICATE = "DUPLICATE"


class AuditAction(str, Enum):
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_PROCESSED = "DOCUMENT_PROCESSED"
    FACT_EXTRACTED = "FACT_EXTRACTED"
    VALIDATION_CREATED = "VALIDATION_CREATED"
    FACT_APPROVED = "FACT_APPROVED"
    FACT_EDITED = "FACT_EDITED"
    FACT_REJECTED = "FACT_REJECTED"
    FACT_SUPERSEDED = "FACT_SUPERSEDED"
    CONFLICT_RESOLVED = "CONFLICT_RESOLVED"
    QUERY_EXECUTED = "QUERY_EXECUTED"
    REPORT_GENERATED = "REPORT_GENERATED"
    PDF_EXPORTED = "PDF_EXPORTED"
    DOCUMENT_DELETED = "DOCUMENT_DELETED"
    SYSTEM_CONFIG_CHANGED = "SYSTEM_CONFIG_CHANGED"
    EVIDENCE_VIEWED = "EVIDENCE_VIEWED"
    CLAIM_INSPECTED = "CLAIM_INSPECTED"
    REPORTGUARD_RUN = "REPORTGUARD_RUN"
    REPORT_BLOCKED = "REPORT_BLOCKED"
    DRAFT_OVERRIDE = "DRAFT_OVERRIDE"


class FileType(str, Enum):
    PDF = "PDF"
    XLSX = "XLSX"
    XLS = "XLS"
    CSV = "CSV"
    TXT = "TXT"
    DOCX = "DOCX"
    PNG = "PNG"
    JPG = "JPG"
    JPEG = "JPEG"
    TIFF = "TIFF"
    UNKNOWN = "UNKNOWN"


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class QualityStatus(str, Enum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    RESOLVED = "RESOLVED"
    SUPERSEDED = "SUPERSEDED"


class QualityIssueType(str, Enum):
    MISSING_REQUIRED_VALUE = "MISSING_REQUIRED_VALUE"
    MISSING_METADATA = "MISSING_METADATA"
    DUPLICATE_DOCUMENT = "DUPLICATE_DOCUMENT"
    DUPLICATE_FACT = "DUPLICATE_FACT"
    CONFLICTING_FIGURES = "CONFLICTING_FIGURES"
    EXTRACTION_ERROR = "EXTRACTION_ERROR"
    LOW_CONFIDENCE_OCR = "LOW_CONFIDENCE_OCR"
    INVALID_NUMBER_FORMAT = "INVALID_NUMBER_FORMAT"
    INVALID_UNIT = "INVALID_UNIT"
    IMPOSSIBLE_NEGATIVE_VALUE = "IMPOSSIBLE_NEGATIVE_VALUE"
    PERIOD_MISMATCH = "PERIOD_MISMATCH"
    MINE_SUBSIDIARY_MISMATCH = "MINE_SUBSIDIARY_MISMATCH"
    AGGREGATION_INCONSISTENCY = "AGGREGATION_INCONSISTENCY"
    UNSUPPORTED_CONVERSION = "UNSUPPORTED_CONVERSION"
    MISSING_SOURCE_EVIDENCE = "MISSING_SOURCE_EVIDENCE"


class ExtractionMethod(str, Enum):
    STRUCTURED_TABLE = "STRUCTURED_TABLE"
    HEURISTIC_PARSER = "HEURISTIC_PARSER"
    REGEX_PATTERN = "REGEX_PATTERN"
    OCR_BLOCK = "OCR_BLOCK"
    LLM_ASSISTED = "LLM_ASSISTED"
    MANUAL_ENTRY = "MANUAL_ENTRY"


class ClaimType(str, Enum):
    EVIDENCE_FACT = "EVIDENCE_FACT"
    DERIVED_CALCULATION = "DERIVED_CALCULATION"
    AI_NARRATIVE = "AI_NARRATIVE"
    RECOMMENDATION = "RECOMMENDATION"
    INTERPRETATION = "INTERPRETATION"
    UNSUPPORTED = "UNSUPPORTED"


class ClaimSupportStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    UNSUPPORTED = "UNSUPPORTED"


class ReportGuardStatus(str, Enum):
    READY = "READY"
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    BLOCKED = "BLOCKED"


class DataScope(str, Enum):
    REAL = "REAL"
    DEMO = "DEMO"
    MIXED = "MIXED"
