"""
Intent classification definitions for Ask MineIntel.
All required intent classes per MineIntel specifications.
"""
from enum import Enum


class QueryIntent(str, Enum):
    GREETING = "GREETING"
    HELP = "HELP"
    CAPABILITY_QUERY = "CAPABILITY_QUERY"
    METRIC_LOOKUP = "METRIC_LOOKUP"
    COMPARISON = "COMPARISON"
    CALCULATION = "CALCULATION"
    TREND_ANALYSIS = "TREND_ANALYSIS"
    FACT_VERIFICATION = "FACT_VERIFICATION"
    DOCUMENT_QUERY = "DOCUMENT_QUERY"
    DOCUMENT_SUMMARY = "DOCUMENT_SUMMARY"
    EXPLANATION = "EXPLANATION"
    PARLIAMENTARY_QUERY = "PARLIAMENTARY_QUERY"
    REPORT_QUERY = "REPORT_QUERY"
    CONFLICT_QUERY = "CONFLICT_QUERY"
    SOURCE_QUERY = "SOURCE_QUERY"
    UNKNOWN = "UNKNOWN"


class AnswerStatus(str, Enum):
    SUCCESS = "SUCCESS"
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    UNVERIFIED_EVIDENCE_EXISTS = "UNVERIFIED_EVIDENCE_EXISTS"
    ERROR = "ERROR"


class ResponseMode(str, Enum):
    STANDARD = "STANDARD"
    QUICK = "QUICK"
    DETAILED = "DETAILED"
    PARLIAMENTARY = "PARLIAMENTARY"
    VERIFICATION = "VERIFICATION"
    COMPARISON = "COMPARISON"
    ANALYST = "ANALYST"
