"""
Phase 10 — Parliamentary Query Mode API
Serves parliamentary-style briefings from grounded evidence.
"""
from fastapi import APIRouter, Depends, Query as FQuery
from sqlalchemy.orm import Session
from typing import Optional

from app.core.database import get_db
from app.services.query_engine import NumberSafeQueryEngine

router = APIRouter(prefix="/parliamentary", tags=["Parliamentary Brief"])

PARLIAMENTARY_TEMPLATE = """
GOVERNMENT OF INDIA
MINISTRY OF COAL
LOK SABHA / RAJYA SABHA — STARRED QUESTION BRIEF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SUBJECT: {subject}

PERIOD: {period}

─────────────────────────────────────────────
A. DIRECT ANSWER
─────────────────────────────────────────────
{direct_answer}

─────────────────────────────────────────────
B. SUPPORTING EVIDENCE
─────────────────────────────────────────────
{evidence_section}

─────────────────────────────────────────────
C. DATA INTEGRITY CERTIFICATE
─────────────────────────────────────────────
Records consulted : {records_used}
Verified evidence : {verified_pct:.1f}%
NumberSafe status : {numbersafe_status}
Confidence score  : {confidence:.1%}

─────────────────────────────────────────────
D. CITATION APPENDIX
─────────────────────────────────────────────
{citation_appendix}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by MineIntel Evidence Intelligence Platform
All figures sourced deterministically from the Evidence Ledger.
No generative hallucination — NumberSafe 2.0 certified.
"""


@router.post("/brief")
def generate_parliamentary_brief(
    query: str = FQuery(..., description="Parliamentary question text"),
    period: str = FQuery("ALL", description="Reporting period (e.g. FY 2024-25)"),
    subsidiary: str = FQuery("ALL", description="Subsidiary (ALL for consolidated)"),
    db: Session = Depends(get_db),
):
    """
    Generates a parliamentary-style question brief with grounded evidence answer,
    citation appendix, and NumberSafe data integrity certificate.
    """
    full_query = query
    if period != "ALL":
        full_query += f" in {period}"
    if subsidiary != "ALL":
        full_query += f" for {subsidiary}"

    result = NumberSafeQueryEngine.execute(
        db=db,
        query_text=full_query,
        scope=f"{subsidiary}_EVIDENCE" if subsidiary != "ALL" else "ALL_EVIDENCE",
        response_mode="PARLIAMENTARY",
    )

    # Build evidence section
    evidence_lines = []
    for i, cite in enumerate(result.get("citations", [])[:10], 1):
        val = cite.get("value", "N/A")
        unit = cite.get("unit", "")
        evidence_lines.append(
            f"  [{i}] {cite.get('metric_code', 'METRIC')}: {val} {unit}\n"
            f"      Source: {cite.get('document_name', 'Document')} "
            f"(Page {cite.get('page_number', 'N/A')}, "
            f"Cell {cite.get('cell_reference', 'N/A')})"
        )

    # Build citation appendix
    citation_lines = []
    for i, cite in enumerate(result.get("citations", [])[:10], 1):
        citation_lines.append(
            f"  Ref [{i}]  Document  : {cite.get('document_name', 'N/A')}\n"
            f"            Metric    : {cite.get('metric_code', 'N/A')}\n"
            f"            Period    : {cite.get('reporting_period', period)}\n"
            f"            Location  : Page {cite.get('page_number', 'N/A')}, "
            f"Sheet: {cite.get('sheet_name', 'N/A')}, "
            f"Cell: {cite.get('cell_reference', 'N/A')}\n"
            f"            Verified  : {'Yes' if cite.get('human_verified') else 'Pending'}"
        )

    records_used = result.get("records_used", 0)
    confidence = result.get("confidence", 0.0)
    numbersafe_status = (
        "DETERMINISTIC SQL — No LLM hallucination" if records_used > 0
        else "INSUFFICIENT EVIDENCE — Manual review required"
    )

    brief_text = PARLIAMENTARY_TEMPLATE.format(
        subject=query.upper()[:120],
        period=period,
        direct_answer=result.get("answer", "Insufficient evidence in the Evidence Ledger for this query."),
        evidence_section="\n".join(evidence_lines) if evidence_lines else "  No structured evidence records available.",
        records_used=records_used,
        verified_pct=min(100.0, confidence * 100),
        numbersafe_status=numbersafe_status,
        confidence=confidence,
        citation_appendix="\n\n".join(citation_lines) if citation_lines else "  No citations available.",
    )

    return {
        "query": query,
        "period": period,
        "subsidiary": subsidiary,
        "brief_text": brief_text,
        "status": result.get("status", "SUCCESS"),
        "records_used": records_used,
        "confidence": confidence,
        "citations": result.get("citations", []),
        "direct_metric_value": result.get("direct_metric_value"),
        "metric_unit": result.get("metric_unit"),
        "calculation": result.get("calculation"),
    }


@router.get("/sample-questions")
def get_sample_parliamentary_questions():
    """Returns pre-built sample parliamentary questions for the demo."""
    return {
        "questions": [
            {
                "id": "q1",
                "question": "What was the total raw coal production of Coal India Limited in FY 2024-25?",
                "period": "FY 2024-25",
                "subsidiary": "ALL",
                "category": "Production",
            },
            {
                "id": "q2",
                "question": "What is the target vs achievement for SECL coal production?",
                "period": "FY 2024-25",
                "subsidiary": "SECL",
                "category": "Target Achievement",
            },
            {
                "id": "q3",
                "question": "What was the overburden removal across all subsidiaries?",
                "period": "FY 2024-25",
                "subsidiary": "ALL",
                "category": "OBR",
            },
            {
                "id": "q4",
                "question": "How many meters of core drilling were completed by CMPDI?",
                "period": "FY 2024-25",
                "subsidiary": "CMPDI",
                "category": "Exploration",
            },
            {
                "id": "q5",
                "question": "What was NCL's coal dispatch in FY 2024-25?",
                "period": "FY 2024-25",
                "subsidiary": "NCL",
                "category": "Dispatch",
            },
        ]
    }
