"""Initial MineIntel schema

Revision ID: c8d7f282d487
Revises: 
Create Date: 2026-09-18 09:53:53.642356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d7f282d487'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('document_category', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('reporting_period', sa.String(length=50), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('sheet_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('processing_progress', sa.Integer(), nullable=True),
    sa.Column('processing_message', sa.String(length=255), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('fact_count', sa.Integer(), nullable=True),
    sa.Column('topic_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_table('evidence_conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('primary_fact_id', sa.String(length=36), nullable=False),
    sa.Column('conflicting_fact_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discrepancy_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_conflicts_conflicting_fact_id'), 'evidence_conflicts', ['conflicting_fact_id'], unique=False)
    op.create_index(op.f('ix_evidence_conflicts_metric_code'), 'evidence_conflicts', ['metric_code'], unique=False)
    op.create_index(op.f('ix_evidence_conflicts_primary_fact_id'), 'evidence_conflicts', ['primary_fact_id'], unique=False)
    op.create_table('generated_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('output_path', sa.String(length=500), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('response_mode', sa.String(length=50), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('evidence_citations', sa.Text(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('fact_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('previous_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_actions_document_id'), 'review_actions', ['document_id'], unique=False)
    op.create_index(op.f('ix_review_actions_fact_id'), 'review_actions', ['fact_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('document_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('raw_metric_name', sa.String(length=255), nullable=True),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('raw_unit', sa.String(length=50), nullable=True),
    sa.Column('reporting_period', sa.String(length=50), nullable=True),
    sa.Column('organization', sa.String(length=100), nullable=False),
    sa.Column('subsidiary', sa.String(length=50), nullable=True),
    sa.Column('coalfield', sa.String(length=100), nullable=True),
    sa.Column('mine', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('cell_reference', sa.String(length=50), nullable=True),
    sa.Column('table_reference', sa.String(length=200), nullable=True),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_facts_coalfield'), 'extracted_facts', ['coalfield'], unique=False)
    op.create_index(op.f('ix_extracted_facts_document_id'), 'extracted_facts', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_facts_metric_code'), 'extracted_facts', ['metric_code'], unique=False)
    op.create_index(op.f('ix_extracted_facts_mine'), 'extracted_facts', ['mine'], unique=False)
    op.create_index(op.f('ix_extracted_facts_numeric_value'), 'extracted_facts', ['numeric_value'], unique=False)
    op.create_index(op.f('ix_extracted_facts_reporting_period'), 'extracted_facts', ['reporting_period'], unique=False)
    op.create_index(op.f('ix_extracted_facts_subsidiary'), 'extracted_facts', ['subsidiary'], unique=False)
    op.create_index(op.f('ix_extracted_facts_validation_status'), 'extracted_facts', ['validation_status'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_document_id'), 'processing_jobs', ['document_id'], unique=False)
    op.create_table('topic_mentions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_mentions_document_id'), 'topic_mentions', ['document_id'], unique=False)
    op.create_index(op.f('ix_topic_mentions_topic_id'), 'topic_mentions', ['topic_id'], unique=False)
    op.create_table('validation_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('fact_id', sa.String(length=36), nullable=True),
    sa.Column('issue_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['extracted_facts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_issues_document_id'), 'validation_issues', ['document_id'], unique=False)
    op.create_index(op.f('ix_validation_issues_fact_id'), 'validation_issues', ['fact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_issues_fact_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_document_id'), table_name='validation_issues')
    op.drop_table('validation_issues')
    op.drop_index(op.f('ix_topic_mentions_topic_id'), table_name='topic_mentions')
    op.drop_index(op.f('ix_topic_mentions_document_id'), table_name='topic_mentions')
    op.drop_table('topic_mentions')
    op.drop_index(op.f('ix_processing_jobs_document_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_extracted_facts_validation_status'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_subsidiary'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_reporting_period'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_numeric_value'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_mine'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_metric_code'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_document_id'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_coalfield'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_review_actions_fact_id'), table_name='review_actions')
    op.drop_index(op.f('ix_review_actions_document_id'), table_name='review_actions')
    op.drop_table('review_actions')
    op.drop_table('query_history')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_evidence_conflicts_primary_fact_id'), table_name='evidence_conflicts')
    op.drop_index(op.f('ix_evidence_conflicts_metric_code'), table_name='evidence_conflicts')
    op.drop_index(op.f('ix_evidence_conflicts_conflicting_fact_id'), table_name='evidence_conflicts')
    op.drop_table('evidence_conflicts')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
